languageCode = "en-us"
title = "DSE Spark Rest API Example"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	description = "DSE Spark Rest API Example"

	logo = "images/asset-hub.svg"
	favicon = "/images/asset-hub.png"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
	github  = "phact/dse-spark-rest-api"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "DSE Spark Rest API Example"
	url    = "/"
	weight = 10
[[menu.main]]
    name   = "Build and Run"
    url    = "buildandrun/"
    weight = 100
